### ISSUE TITLE
Error on import into block: Unexpected token (175:6) You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by 8bit-echo** [vermiliondesign/gutenberg-post-selector#2]
Issue:
when using `import PostSelector from '@vermilion/post-selector'` create-guten-block throws error:

```
Module parse failed: Unexpected token (175:6)
You may need an appropriate loader to handle this file type.
|     // show each post in the list.
|     return (
|       <ul>
|         {this.props.posts.map((post, i) => (
|           <li style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', flexWrap: 'nowrap' }}>
```

Steps to reproduce: 

`npm install @vermilion/post-selector`
`import PostSelector from '@vermilion/post-selector'`
`npm start`

**Comment by braco** [comment]
This should probably be transpiled away from jsx for bundling

**Comment by 8bit-echo** [comment]
Yeah, I think you’re right. When I copy the file into the project’s src folder, it works fine, but not when importing from node_modules.

**Comment by braco** [comment]
That makes sense, it's out of Webpack's scope

**Comment by tyrann0us** [comment]
@8bit-echo, do you have any plans to include compiled files? Currently, the package is not usable if you don't want to install it manually.
Thanks!

_CC @braco_

**Comment by 8bit-echo** [comment]
I did intend to include the compiled code initially, but there's a fundamental flaw in this block's execution. This block will only pull content as it exists at the time of creation. It won't update if the posts that it's referencing change. We're working on moving this block to use `<ServerSideRender />`, but it will involve doing some manual work in PHP with the data it sends to the server.

**Comment by 8bit-echo** [comment]
@tyrann0us @braco. I've updated the npm version to 1.0.1 and you should be able to import this now and use it as described in the readme file.

**Comment by 8bit-echo** [comment]
Haven't heard back for a while. Closing this issue unless something else pops up.
