### ISSUE TITLE
Update package on npm registry

### ISSUE THREAD

**Issue by tyrann0us** [vermiliondesign/gutenberg-post-selector#6]
The version on https://www.npmjs.com/package/@vermilion/post-selector ist not up to date. Could you please update it?
Thanks!

**Comment by 8bit-echo** [comment]
There's no PHP code to import in this package.. Unless I'm missing something here (?)

**Comment by tyrann0us** [comment]
I'm sorry. I mostly work with PHP libraries, so I confused Packagist.org with the npm registry. Since you updated the package over there (https://github.com/vermiliondesign/gutenberg-post-selector/issues/2#issuecomment-457399724) I'm closing this.
